version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      {{ pihole_default_environment | combine(pihole_environment) | to_nice_yaml | indent(width=6)}}
    volumes:
      - './etc/pihole:/etc/pihole'
      - './etc/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

  dnscrypt:
    container_name: dnscrypt-proxy
    network_mode: host
    image: klutchell/dnscrypt-proxy:latest
    restart: unless-stopped
    environment:
      TZ: 'Europe/Paris'
    volumes:
      - './etc/dnscrypt-proxy/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'