version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:{{ pihole_docker_version }}
    network_mode: host
    environment:
      {{ pihole_default_environment | combine(pihole_environment) | to_nice_yaml | indent(width=6)}}
    volumes:
      - './etc/pihole:/etc/pihole'
      - './etc/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    # disable lighttpd bind setup, keep it listening on 0.0.0.0 as per default
    # permits to connect to host or vip address at the same time
    entrypoint: ['/bin/bash', '-c', 'sed -i "s/^setup_lighttpd_bind/#setup_lighttpd_bind/" /usr/local/bin/_startup.sh ; /s6-init']
  dnscrypt:
    container_name: dnscrypt-proxy
    network_mode: host
    image: klutchell/dnscrypt-proxy:{{ pihole_dnscrypt_docker_version }}
    restart: unless-stopped
    environment:
      TZ: '{{ (pihole_default_environment | combine(pihole_environment))["TZ"] }}'
    volumes:
      - './etc/dnscrypt-proxy/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'