- name: 'Enable nonlocal IP binding'
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: 'net.{{ item }}.ip_nonlocal_bind = 1'
  loop:
    - ipv4
    - ipv6
  notify: Reload sysctl config

- name: Flush handlers
  meta: flush_handlers

- name: Install keepalived
  ansible.builtin.apt:
    force_apt_get: yes
    name: keepalived

- name: Copy check_pihole.sh
  ansible.builtin.copy:
    dest: /etc/keepalived/check_pihole.sh
    src: check_pihole.sh
    mode: 0755

- name: Configure keepalived
  ansible.builtin.template:
    dest: /etc/keepalived/keepalived.conf
    src: keepalived.j2
    mode: 0644
  notify: Restart keepalived service

- name: Flush handlers
  meta: flush_handlers