pihole_default_environment:
  TZ: 'Europe/Paris'
  FTLCONF_LOCAL_IPV4: '{{ ansible_default_ipv4.address }}'
  FTLCONF_REPLY_ADDR6: '{{ ansible_default_ipv6.address }}'
  PIHOLE_DNS_: "127.0.0.1#5353;::1#5656"
  VIRTUAL_HOST: pihole.your.domain.com
  INTERFACE: '{{ ansible_default_ipv4.interface}}'