pihole_default_environment:
  TZ: 'Europe/Paris'
  FTLCONF_LOCAL_IPV4: "{{ pihole_vip_ipv4.split('/')[0] }}"
  FTLCONF_LOCAL_IPV6: "{{ pihole_vip_ipv6.split('/')[0] }}"
  PIHOLE_DNS_: "127.0.0.1#{{ pihole_dnscrypt_port|string + pihole_dnscrypt_ipv6|bool|ternary(';::1#'+pihole_dnscrypt_port|string,'') }}"
  VIRTUAL_HOST: pi.hole
  INTERFACE: '{{ ansible_default_ipv4.interface}}'