- name: Update apt packages
  apt:
    force_apt_get: yes
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: dist

- name: Check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Install dependencies
  apt:
    force_apt_get: yes
    name:
      - docker-compose
      - git
      - rsync

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

- name: Disable systemd-resolved stub dns
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener='
    line: DNSStubListener=no
  register: _resolved
  become: yes

- name: Restart systemd-resolved if changed
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  when: _resolved.changed
  become: yes

- name: Reboot
  reboot:
  when: reboot_required.stat.exists