- name: Update apt packages
  ansible.builtin.apt:
    force_apt_get: yes
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: dist

- name: Check if reboot is needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Install dependencies
  ansible.builtin.apt:
    force_apt_get: yes
    name:
      - docker-compose
      - git
      - rsync

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

- name: Disable systemd-resolved stub dns
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener='
    line: DNSStubListener=no
  ignore_errors: yes
  register: _resolved

- name: Restart systemd-resolved if changed
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  when: _resolved.changed

- name: Reboot
  ansible.builtin.reboot:
  when: reboot_required.stat.exists