- name: Create docker directories
  file:
    path: 'pihole/etc/{{ item }}'
    recurse: true
    state: directory
  loop:
    - dnsmasq.d
    - pihole
    - dnscrypt-proxy

- name: copy docker-compose.yaml
  template:
    src: docker-compose.yaml
    dest: pihole/docker-compose.yaml

- name: copy dsncrypt-proxy config file
  template:
    src: dnscrypt-proxy.toml
    dest: pihole/etc/dnscrypt-proxy/dnscrypt-proxy.toml

- name: Stop keepalived service
  service:
    name: keepalived
    state: stopped
  changed_when: no
  become: true

- name: Create and start pihole
  community.docker.docker_compose:
    project_src: pihole
    pull: yes

- name: Start keepalived service
  service:
    name: keepalived
    state: started
  changed_when: no
  become: true

- name: Check pihole container
  uri:
    url: http://localhost
  register: result
  until: result.status == 200
  retries: 5
  delay: 10
  when: not ansible_check_mode

- name: Remove old image versions
  community.docker.docker_prune:
    images: yes
    images_filters:
      dangling: false
  become: true